<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>InstantMessage</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.imessage-0.0.1.min.js"></script>
    <script type="text/javascript">
    $(function(){
		
		$('#messages-container-base').imessage({
			url: '<?php echo $this->baseUrl(); ?>/index/ajaximessage',
			timeout: 15
		});
		
    	$('#messages-container').imessage({
    		url: '<?php echo $this->baseUrl(); ?>/index/ajaximessage',
    		timeout: 10,
    		messageWrapper: '<div>',

    		onRequest: function () {
    			$('#imessage-loader').show();
    		},
    		onResponse: function (data) {
    			$('#imessage-loader').hide();
    			$('#imessage-unread').text(parseInt($('#imessage-unread').text()) + $(data['messages']).length);
    		},
    		onMessageHover: function () {
    			if ($(this).hasClass('imessage-item-new')) {
    				$('#imessage-unread').text(parseInt($('#imessage-unread').text()) - 1);
    			}
    			
    			$(this).removeClass('imessage-item-new');
    		},
    		onMessageClick: function () {},
    		onBeforeInsert: function (message) {
    			message.addClass('imessage-item-new');
    		}
    	});
    	
    	$('#header-base').click(function() {
    		$('#messages-container-base').toggle();
    	});
    	$('#header').click(function() {
    		$('#messages-container').toggle();
    	});
    })
    </script>
    
    <style type="text/css">
    	.base { right: auto; left: 20px;}
    	.window {position: absolute; width: 200px; bottom: 0px; right: 30px; border: 1px solid #254588; border-bottom: none;}
    	.window .header {background: #6D84B4; height: 19px; padding-top: 2px; cursor: pointer;}
    	#imessage-loader {display: none;}
		#imessage-unread {color: #ffffff; font-weight: bold; float: right; margin-right: 4px;}
    	.window .messages-container {overflow: auto;height: 278px;}
    	.window .messages-container .imessage-item {background: #e5eaf1; padding: 3px; border: 1px solid #cccccc; border-top: none;}
    	.imessage-item .name {font-weight: bold;}
    	.imessage-item-new {background: #ece9d8!important;}
    	.clear {clear: both}
    </style>
</head>

<body>
	
	<div class="window base">
		<div class="header" id="header-base"></div>
		<div class="clear"></div>
		<div id="messages-container-base" class="messages-container"></div>
	</div>
	
	<div class="window">
		<div class="header" id="header"><img id="imessage-loader" src="<?php echo $this->baseUrl(); ?>/img/loader.gif" /> <div id="imessage-unread">0</div></div>
		<div class="clear"></div>
		<div id="messages-container" class="messages-container"></div>
	</div>
	
</body>
</html>