<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title>InstantMessage</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js"></script>
    
    <style>
    	* {margin: 0; padding: 0;}
    	
    	.window {width: 400px; border: 1px solid #eee;}
    	.window .header {height: 50px; border-bottom: 1px solid #eee;}
		.window {margin: 0 auto}
		
		.message {margin: 5px; background: #eee;}
    	.message .title {height: 30px; padding: 4px;}
    	.message .title .time {float: left; width: 70px; font-size: 12px;}
    	.message .text {color: #447AA4; font-size: 14px; padding: 4px;}
    </style>
    
    <script type="text/javascript">
    	$(function() {
    		setInterval(function() {
    			$('.window .body .message').css('background', '#eee');
    			$.get('/index/ajaxtweet', function (data) {
    				if (data != undefined && data != '') { 
						$('.window .body .message:first').before(data);
						$('.window .body .message:first').css('background', '#ddd');
						$('#count').text(parseInt($('#count').text()) + 1);
					}
    			});
    			
    		}, 8000);
    	});
    	
    </script>
</head>

<body>
	<div class="window">
		<div class="header">
			<h2>Public tweets: (<span id="count"><?php echo $this->count;?></span>)</h2>
		</div>
		<div class="body">
			<?php echo $this->renderMessages($this->tweets); ?>
		</div>
	</div>
</body>
</html>